### ISSUE TITLE
CODE?

### ISSUE THREAD

**Issue by ombhatt2** [RidwanA123/Crazy-Error#1]
CODE?

**Comment by ombhatt2** [comment]
Where is the code?

**Comment by ombhatt2** [comment]
I dont see it

**Comment by ombhatt2** [comment]
Please let me know

**Comment by ombhatt2** [comment]
Whats the error?

**Comment by RidwanA123** [comment]
> Whats the error?

You

**Comment by ombhatt2** [comment]
Thats mean

**Comment by ombhatt2** [comment]
Ok but how is the error me?

**Comment by ombhatt2** [comment]
WARNING: This github may contain offensive language!

**Comment by ombhatt2** [comment]
WARNING: This github may contain offensive language!

**Comment by ombhatt2** [comment]
WARNING: This github may contain offensive language!

**Comment by Luke-zhang-04** [comment]
Ah, the classic talk to yourself. Please stop.

**Comment by ombhatt2** [comment]
Why should I stop?

**Comment by Luke-zhang-04** [comment]
You're making a fool out of yourself

**Comment by RidwanA123** [comment]
> Why should I stop?

This shows your mental age and the strength of your braincells.

**Comment by Luke-zhang-04** [comment]
"CODE?"? What? Please stop and use words properly you troglodyte, do you think we were given the freedom of speech just to spew random words that have no meaning that doesn't even correllate to the topic of the conversation? Like please you always complain about why no one talks to you or no one expresses their opinions on you because you're always spewing random crap like "CODE?" "thats mean" "BIZZARE AND ILLEGAL!" and when you try to explain what it is and you just say that it's funny like what? What the heck is funny about that do you think you'll just become a stand-up comedian that will get a standing ovation just because you said "CODE?" in the stage? HELL NO, so please stop and use words properly
